### ISSUE TITLE
Seeming race condition with iterator: "libc++abi.dylib: pure virtual method called"

### ISSUE THREAD

**Issue by lsb** [Factual/clj-leveldb#7]
When I use Clojure 1.6 with 0.1.1, on OS X, it looks like there's a race condition in the iterator. When I do `(count (clj-leveldb/iterator <my-db>))` I almost immediately get an error, libc++abi.dylib: pure virtual method called.

When I `(count (map (fn [x] (Thread/sleep 1) x) (clj-leveldb/iterator <my-db>))` I don't see this problem.

When I use Clojure 1.5.1 with 0.1.0, on OS X, everything works great.

**Comment by ztellman** [comment]
Unfortunately, we're not in a position to debug the underlying database, where this issue apparently exists.  We could try to target a more recent version of leveldb, but in our experience it's prohibitively difficult to update the underlying leveldbjni dependency ourselves.  

I'll leave this issue open, since it's clearly something we'd like to fix, but I'm not sure there's anything we can do in the near term.

**Comment by lsb** [comment]
BTW this is still present on Clojure 1.7.0 with 0.1.1
